export default [
  {
    cursor: '',
    code: '0010-0056',
    name: '株式会社レコチョク',
    country: 'JP',
    month: '',
    created: '',
    usageCount: '',
    income: '',
    memberCount: '',
    reportedAmount: '5,919,592',
    amount: '5,919,592',
    previousAmount: '839,760',
    status: '',
    action: '',
    _showChildren: true,
    _children: [
      {
        cursor: '',
        code: 'XXXX1',
        name: 'レコチョク MusicStore',
        country: 'JP',
        month: '',
        created: 'DL/通常/ハイレゾ/映像',
        usageCount: '',
        income: '',
        memberCount: '',
        reportedAmount: '744,160',
        amount: '744,160',
        previousAmount: '91,000',
        status: '',
        action: '',
        _showChildren: true,
        _children: [
          {
            cursor: '',
            code: '1',
            name: 'シングル',
            country: 'JP',
            month: '2019/4',
            created: '2019/5/10 12:35',
            usageCount: '',
            income: '',
            memberCount: '',
            reportedAmount: '100,000',
            amount: '100,000',
            previousAmount: '5,000',
            status: '完了',
            action: '',
          },
          {
            cursor: '',
            code: '2',
            name: 'アルバム',
            country: 'JP',
            month: '2019/4',
            created: '2019/5/10 12:35',
            usageCount: '',
            income: '',
            memberCount: '',
            reportedAmount: '120,000',
            amount: '120,000',
            previousAmount: '6,000',
            status: '完了',
            action: '',
          },
          {
            cursor: '',
            code: '3',
            name: 'ビデオクリップ',
            country: 'JP',
            month: '2019/4',
            created: '2019/5/10 12:35',
            usageCount: '',
            income: '',
            memberCount: '',
            reportedAmount: '120,000',
            amount: '120,000',
            previousAmount: '6,000',
            status: '完了',
            action: '',
          },
        ],
      },
      {
        cursor: '',
        code: 'XXXX2',
        name: 'd ミュージック',
        country: 'JP',
        month: '',
        created: 'DL/ハイレゾ/映像',
        usageCount: '',
        income: '',
        memberCount: '',
        reportedAmount: '905,748',
        amount: '905,748',
        previousAmount: '131,040',
        status: '',
        action: '',
        _children: [
          {
            cursor: '',
            code: '1',
            name: 'シングル',
            country: 'JP',
            month: '2019/4',
            created: '2019/5/10 12:35',
            usageCount: '',
            income: '',
            memberCount: '',
            reportedAmount: '100,000',
            amount: '100,000',
            previousAmount: '5,000',
            status: '完了',
            action: '',
          },
          {
            cursor: '',
            code: '2',
            name: 'アルバム',
            country: 'JP',
            month: '2019/4',
            created: '2019/5/10 12:35',
            usageCount: '',
            income: '',
            memberCount: '',
            reportedAmount: '120,000',
            amount: '120,000',
            previousAmount: '6,000',
            status: '完了',
            action: '',
          },
          {
            cursor: '',
            code: '3',
            name: 'ビデオクリップ',
            country: 'JP',
            month: '2019/4',
            created: '2019/5/10 12:35',
            usageCount: '',
            income: '',
            memberCount: '',
            reportedAmount: '120,000',
            amount: '120,000',
            previousAmount: '6,000',
            status: '完了',
            action: '',
          },
        ],
      },
    ],
  },
  {
    cursor: '',
    code: '0010-0057',
    name: 'アップル',
    country: 'JP',
    month: '',
    created: '',
    usageCount: '',
    income: '',
    memberCount: '',
    reportedAmount: '5,919,592',
    amount: '5,919,592',
    previousAmount: '839,760',
    status: '',
    action: '',
    _children: [
      {
        cursor: '',
        code: 'XXXX1',
        name: 'レコチョク MusicStore',
        country: 'JP',
        month: '',
        created: 'DL/通常/ハイレゾ/映像',
        usageCount: '',
        income: '',
        memberCount: '',
        reportedAmount: '744,160',
        amount: '744,160',
        previousAmount: '91,000',
        status: '',
        action: '',
        _children: [
          {
            cursor: '',
            code: '1',
            name: 'シングル',
            country: 'JP',
            month: '2019/4',
            created: '2019/5/10 12:35',
            usageCount: '',
            income: '',
            memberCount: '',
            reportedAmount: '100,000',
            amount: '100,000',
            previousAmount: '5,000',
            status: '完了',
            action: '',
          },
          {
            cursor: '',
            code: '2',
            name: 'アルバム',
            country: 'JP',
            month: '2019/4',
            created: '2019/5/10 12:35',
            usageCount: '',
            income: '',
            memberCount: '',
            reportedAmount: '120,000',
            amount: '120,000',
            previousAmount: '6,000',
            status: '完了',
            action: '',
          },
          {
            cursor: '',
            code: '3',
            name: 'ビデオクリップ',
            country: 'JP',
            month: '2019/4',
            created: '2019/5/10 12:35',
            usageCount: '',
            income: '',
            memberCount: '',
            reportedAmount: '120,000',
            amount: '120,000',
            previousAmount: '6,000',
            status: '完了',
            action: '',
          },
        ],
      },
      {
        cursor: '',
        code: 'XXXX2',
        name: 'd ミュージック',
        country: 'JP',
        month: '',
        created: 'DL/ハイレゾ/映像',
        usageCount: '',
        income: '',
        memberCount: '',
        reportedAmount: '905,748',
        amount: '905,748',
        previousAmount: '131,040',
        status: '',
        action: '',
        _children: [
          {
            cursor: '',
            code: '1',
            name: 'シングル',
            country: 'JP',
            month: '2019/4',
            created: '2019/5/10 12:35',
            usageCount: '',
            income: '',
            memberCount: '',
            reportedAmount: '100,000',
            amount: '100,000',
            previousAmount: '5,000',
            status: '完了',
            action: '',
          },
          {
            cursor: '',
            code: '2',
            name: 'アルバム',
            country: 'JP',
            month: '2019/4',
            created: '2019/5/10 12:35',
            usageCount: '',
            income: '',
            memberCount: '',
            reportedAmount: '120,000',
            amount: '120,000',
            previousAmount: '6,000',
            status: '完了',
            action: '',
          },
          {
            cursor: '',
            code: '3',
            name: 'ビデオクリップ',
            country: 'JP',
            month: '2019/4',
            created: '2019/5/10 12:35',
            usageCount: '',
            income: '',
            memberCount: '',
            reportedAmount: '120,000',
            amount: '120,000',
            previousAmount: '6,000',
            status: '完了',
            action: '',
          },
        ],
      },
    ],
  },
  {
    cursor: '',
    code: '0010-0058',
    name: '子供なしはどう見える',
    country: 'JP',
    month: '',
    created: '',
    usageCount: '',
    income: '',
    memberCount: '',
    reportedAmount: '5,919,592',
    amount: '5,919,592',
    previousAmount: '839,760',
    status: '',
    action: '',
  },
];
